### PR TITLE
Fix for testing error pages

### PR DESCRIPTION
**Pull request by martinsvoboda**
Cannot test error pages, because urlopen raise http exception
`url_available(url='http://doesnotexist.com', expected_code=404) # raise exception`

### CODE REVIEW

**Comment by tricoder42** [comment]
Good catch! Thank you

Could you please provide a simple test?

**Comment by tricoder42** [comment]
I tried to reproduce it, but without success.
1. http://doesnotexist.com _does_ exists, but I used http://reallydoesnotexist.com :smile: 
2. `urlopen` raises `URLError` which doesn't have `code` attribute (https://docs.python.org/3/library/urllib.error.html#urllib.error.URLError). Should we assume, that raising URLError equals to 404?

My test:

``` python
    # django-smoked/tests/unit/builtin_tests/test_url.py

    def test_nonexisting_url(self):
        url_available('http://reallydoesnotexist.com', expected_code=404)
```

Traceback:

```
> raise URLError(err)
E URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
```

_UPDATE_:
Ok, `urlopen` can't handle unknown domains (it throws `URLError`), but unknown URL throws `HTTPError`, ex. http://google.com/this-is-not-a-love-song

``` python

    def test_nonexisting_url(self):
        url_available('http://google.com/this-is-not-a-love-song', expected_code=404)
```

Your patch handles "not found" URLs well.

How to handle unknown domains? Assume that raised URLError equals to 404?

**Comment by martinsvoboda** [comment]
Oh I see, it's more complicated. If domain doesn't exist, urlopen raise URLError. If domain exists, but page doesn't, urlopen raise HTTPError. Check:

``` python
url_available(url='http://www.google.com/pagenotexists/', expected_code=404)
# raise HTTPError: HTTP Error 404: Not Found
```

**Comment by tricoder42** [comment]
Yes, that's it (see comment update above. We only have to decide what to do with `URLError` exception)

I've just added two (failing) tests for both cases in 9871c2795

**Comment by martinsvoboda** [comment]
Makes sense not catch URLError. `url_available` needs http code, if testing URL doesn't return valid HTTP response, raise URLError.

**Comment by tricoder42** [comment]
Ok, thank you!

**Pull request merged**
